---
title: "Asset pricing group project"
author: "Felix Hemsted"
date: "25 November 2018"
output: html_document
---

```{r}

knitr::opts_chunk$set(echo = TRUE)
```


#Getting data and setup

```{r setupData}
library(tidyverse)
library(lubridate)
library(knitr)

factors25<-read_csv("25_Portfolios_5x5.CSV",skip=15,n_max = 1107) %>% 
  rename(Date = X1) %>% 
  gather(key = "Portfolio",value = "Value",-Date) %>% 
  mutate("Size" = str_split_fixed(Portfolio," ",2)[,1],"B/M" = str_split_fixed(Portfolio," ",2)[,2])



#getting market performance and risk free rate

marketAndRiskFree<-read_csv("F-F_Research_Data_5_Factors_2x3.CSV",skip=3,n_max = 663) %>% 
  rename(Date = X1,MKT = "Mkt-RF") %>% select(Date,MKT,RF) %>% 
  mutate(Date = as.numeric(Date)) %>% 
  mutate(MKT = as.numeric(MKT),RF = as.numeric(RF))

firstCorrelations<-factors25 %>% 
  filter(Date>=196401&Date<199301) %>% 
  left_join(marketAndRiskFree) %>% 
  mutate("excessReturn" = Value - RF)

groupings<-unique(factors25$Portfolio)


for(i in 1:length(groupings)){
  dataNeeded<-filter(firstCorrelations,Portfolio == groupings[i])
  
  model<-lm(formula = Value~MKT,data=dataNeeded)
  dataNeeded$prediction<-predict(model,dataNeeded)
  
  modelSummary<-summary(model)
  
  beta<-modelSummary$coefficients["MKT","Estimate"]
  alpha<-modelSummary$coefficients["(Intercept)","Estimate"]
  alphaSignificance<-modelSummary$coefficients["(Intercept)","Pr(>|t|)"]
  meanReturn<-mean(dataNeeded$excessReturn)
  r2<-modelSummary$r.squared
  tempDF<-data.frame("Size" = unique(dataNeeded$Size),"B/M" = unique(dataNeeded$`B/M`),"meanReturn" = meanReturn,"alpha" = alpha,"alphaSignificance" = alphaSignificance,"beta" = beta,"r2" = r2,stringsAsFactors = F)
  
  if(exists("permDF")){
    permDF<-full_join(permDF,tempDF,by=names(tempDF))
  }else{
    permDF<-tempDF
  }
}


meanReturnTable<-permDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,meanReturn) %>% 
  spread(key = "B.M",value = "meanReturn")


kable(meanReturnTable)

betaTable<-permDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,beta) %>% 
  spread(key = "B.M",value = "beta")


kable(betaTable)

alphaTable<-permDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alpha) %>% 
  spread(key = "B.M",value = "alpha")



kable(alphaTable)
options(scipen = 0)

alphaSignificanceTable<-permDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alphaSignificance) %>% 
  spread(key = "B.M",value = "alphaSignificance")


kable(alphaSignificanceTable)

r2<-permDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,r2) %>% 
  spread(key = "B.M",value = "r2")

kable(r2)

##daily

factors25Daily<-read_csv("25_Portfolios_5x5_Daily.CSV",skip = 18,n_max = 23428) %>% 
  rename(Date = X1) %>% 
  gather(key = "Portfolio",value = "Value",-Date) %>% 
  mutate("Size" = str_split_fixed(Portfolio," ",2)[,1],"B/M" = str_split_fixed(Portfolio," ",2)[,2])


marketAndRiskFreeDaily<-read_csv("F-F_Research_Data_5_Factors_2x3_daily.CSV",skip=3) %>% 
  rename(Date = X1,MKT = "Mkt-RF") %>% select(Date,MKT,RF) %>% 
  mutate(Date = as.numeric(Date)) %>% 
  mutate(MKT = as.numeric(MKT),RF = as.numeric(RF))

firstCorrelationsDaily<-factors25Daily %>% 
  filter(Date>=19640101&Date<19930104)%>% 
  left_join(marketAndRiskFreeDaily) %>% 
  mutate("excessReturn" = Value - RF)

groupingsDaily<-unique(factors25Daily$Portfolio)

for(i in 1:length(groupingsDaily)){
  dataNeeded<-filter(firstCorrelationsDaily,Portfolio == groupingsDaily[i])
  
  model<-lm(formula = Value~MKT,data=dataNeeded)
  dataNeeded$prediction<-predict(model,dataNeeded)
  
  modelSummary<-summary(model)
  
  beta<-modelSummary$coefficients["MKT","Estimate"]
  alpha<-modelSummary$coefficients["(Intercept)","Estimate"]
  alphaSignificance<-modelSummary$coefficients["(Intercept)","Pr(>|t|)"]
  meanReturn<-mean(dataNeeded$excessReturn)
  r2<-modelSummary$r.squared
  tempDF<-data.frame("Size" = unique(dataNeeded$Size),"B/M" = unique(dataNeeded$`B/M`),"meanReturn" = meanReturn,"alpha" = alpha,"alphaSignificance" = alphaSignificance,"beta" = beta,"r2" = r2,stringsAsFactors = F)
  
  if(exists("permDFDaily")){
    permDFDaily<-full_join(permDFDaily,tempDF,by=names(tempDF))
  }else{
    permDFDaily<-tempDF
  }
}


meanReturnTableDaily<-permDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,meanReturn) %>% 
  spread(key = "B.M",value = "meanReturn")


kable(meanReturnTableDaily)

betaTableDaily<-permDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,beta) %>% 
  spread(key = "B.M",value = "beta")


kable(betaTableDaily)

alphaTableDaily<-permDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alpha) %>% 
  spread(key = "B.M",value = "alpha")



kable(alphaTableDaily)
options(scipen = 0)

alphaSignificanceTableDaily<-permDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alphaSignificance) %>% 
  spread(key = "B.M",value = "alphaSignificance")


kable(alphaSignificanceTableDaily)

r2Daily<-permDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,r2) %>% 
  spread(key = "B.M",value = "r2")

kable(r2Daily)

```


#Excess returns

```{r excess}
firstCorrelations1<-permDF %>% 
  rename("B/M" = "B.M") %>% 
  right_join(firstCorrelations) %>% 
  mutate(Predicted_return = beta * (MKT-RF) - RF)


ggplot(firstCorrelations1,aes(x=Predicted_return,y=excessReturn))+geom_point()+geom_abline(slope=1,colour="#E41A1C")

firstCorrelations1Daily<-permDFDaily %>% 
  rename("B/M" = "B.M") %>% 
  right_join(firstCorrelationsDaily)%>% 
  mutate(Predicted_return = beta * (MKT-RF) - RF)

ggplot(firstCorrelations1Daily,aes(x=Predicted_return,y=excessReturn))+geom_point()+geom_abline(slope=1,colour="#E41A1C")
```


#Dates after F-F study

```{r datesAfter}
secondCorrelations<-factors25 %>% 
  filter(Date>=199301&Date<201501)%>% 
  left_join(marketAndRiskFree) %>% 
  mutate("excessReturn" = Value - RF)

for(i in 1:length(groupings)){
  dataNeeded<-filter(secondCorrelations,Portfolio == groupings[i])
  
  model<-lm(formula = Value~MKT,data=dataNeeded)
  dataNeeded$prediction<-predict(model,dataNeeded)
  
  modelSummary<-summary(model)
  
  beta<-modelSummary$coefficients["MKT","Estimate"]
  alpha<-modelSummary$coefficients["(Intercept)","Estimate"]
  alphaSignificance<-modelSummary$coefficients["(Intercept)","Pr(>|t|)"]
  meanReturn<-mean(dataNeeded$excessReturn)
  r2<-modelSummary$r.squared
  tempDF<-data.frame("Size" = unique(dataNeeded$Size),"B/M" = unique(dataNeeded$`B/M`),"meanReturn" = meanReturn,"alpha" = alpha,"alphaSignificance" = alphaSignificance,"beta" = beta,"r2" = r2,stringsAsFactors = F)
  
  if(exists("secondPermDF")){
    secondPermDF<-full_join(secondPermDF,tempDF,by=names(tempDF))
  }else{
    secondPermDF<-tempDF
  }
}


secondmeanReturnTable<-secondPermDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,meanReturn) %>% 
  spread(key = "B.M",value = "meanReturn")


kable(secondmeanReturnTable)

secondbetaTable<-secondPermDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,beta) %>% 
  spread(key = "B.M",value = "beta")


kable(secondbetaTable)

secondalphaTable<-secondPermDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alpha) %>% 
  spread(key = "B.M",value = "alpha")



kable(secondalphaTable)
options(scipen = 0)

secondalphaSignificanceTable<-secondPermDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alphaSignificance) %>% 
  spread(key = "B.M",value = "alphaSignificance")


kable(secondalphaSignificanceTable)

secondr2<-secondPermDF %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,r2) %>% 
  spread(key = "B.M",value = "r2")

kable(secondr2)

secondCorrelationsDaily<-factors25Daily %>% 
   filter(Date>=19930104&Date<20150102) %>% 
  left_join(marketAndRiskFreeDaily) %>% 
  mutate("excessReturn" = Value - RF)

for(i in 1:length(groupings)){
  dataNeeded<-filter(secondCorrelationsDaily,Portfolio == groupings[i])
  
  model<-lm(formula = Value~MKT,data=dataNeeded)
  dataNeeded$prediction<-predict(model,dataNeeded)
  
  modelSummary<-summary(model)
  
  beta<-modelSummary$coefficients["MKT","Estimate"]
  alpha<-modelSummary$coefficients["(Intercept)","Estimate"]
  alphaSignificance<-modelSummary$coefficients["(Intercept)","Pr(>|t|)"]
  meanReturn<-mean(dataNeeded$excessReturn)
  r2<-modelSummary$r.squared
  tempDF<-data.frame("Size" = unique(dataNeeded$Size),"B/M" = unique(dataNeeded$`B/M`),"meanReturn" = meanReturn,"alpha" = alpha,"alphaSignificance" = alphaSignificance,"beta" = beta,"r2" = r2,stringsAsFactors = F)
  
  if(exists("secondPermDFDaily")){
    secondPermDFDaily<-full_join(secondPermDFDaily,tempDF,by=names(tempDF))
  }else{
    secondPermDFDaily<-tempDF
  }
}


secondmeanReturnTableDaily<-secondPermDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,meanReturn) %>% 
  spread(key = "B.M",value = "meanReturn")


kable(secondmeanReturnTableDaily)

secondbetaTableDaily<-secondPermDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,beta) %>% 
  spread(key = "B.M",value = "beta")


kable(secondbetaTableDaily)

secondalphaTableDaily<-secondPermDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alpha) %>% 
  spread(key = "B.M",value = "alpha")



kable(secondalphaTableDaily)
options(scipen = 0)

secondalphaSignificanceTabledaily<-secondPermDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,alphaSignificance) %>% 
  spread(key = "B.M",value = "alphaSignificance")


kable(secondalphaSignificanceTabledaily)

secondr2daily<-secondPermDFDaily %>% 
  mutate(Size = factor(Size,levels = c("SMALL","ME1","ME2","ME3","ME4","ME5","BIG")),
         B.M = factor(B.M,levels = c("LoBM","BM1","BM2","BM3","BM4","BM5","HiBM"))) %>% 
  select(Size,B.M,r2) %>% 
  spread(key = "B.M",value = "r2")

kable(secondr2daily)
```


##Charts

```{r secondCharts,width=10,height=10}
secondCorrelations1<-secondPermDF %>% 
  rename("B/M" = "B.M") %>% 
  right_join(secondCorrelations) %>% 
  mutate(Predicted_return = beta * (MKT-RF) - RF)


ggplot(secondCorrelations1,aes(x=Predicted_return,y=excessReturn))+geom_point()+geom_abline(slope=1,colour="#E41A1C")


secondCorrelationsDaily1<-secondPermDFDaily %>% 
    rename("B/M" = "B.M") %>% 
  right_join(secondCorrelationsDaily) %>% 
  mutate(Predicted_return = beta * (MKT-RF) - RF)

ggplot(secondCorrelationsDaily1,aes(x=Predicted_return,y=excessReturn))+geom_point()+geom_abline(slope=1,colour="#E41A1C")

```
